# Generated by Django 4.1.7 on 2023-07-05 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_setup', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', through='model_setup.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
