# Generated by Django 4.1 on 2023-07-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_setup', '0004_alter_like_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
