# Generated by Django 4.1 on 2023-07-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_setup', '0006_post_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
